name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@v1
        with:
          host: 85.198.101.184
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/api-serp.equity.su

            git pull origin main

            composer install --no-dev --optimize-autoloader --no-interaction

            cd frontend
            npm install
            npx vite build
            rsync -a --delete dist/ /var/www/serp.equity.su/
            cd ..

            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan event:cache

            sudo supervisorctl restart serp-panel-worker:*
